const SET_USERS_PROFILE = 'SET_USERS_PROFILE';
const DELETE_USER_PROFILE = 'DELETE_USER_PROFILE';
const SET_IS_LOADING_USERS_PROFILE = 'SET_IS_LOADING_USERS_PROFILE';
const SET_ERROR_USERS_PROFILE = 'SET_ERROR_USERS_PROFILE';
const CLEAR_ERROR_USERS_PROFILE = 'CLEAR_ERROR_USERS_PROFILE';
const CLEAR_ALL_USERS_PROFILE = 'CLEAR_ALL_USERS_PROFILE';

export {
    SET_USERS_PROFILE,
    DELETE_USER_PROFILE,
    SET_IS_LOADING_USERS_PROFILE,
    SET_ERROR_USERS_PROFILE,
    CLEAR_ERROR_USERS_PROFILE,
    CLEAR_ALL_USERS_PROFILE,
};
